/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sedifusov2;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jordi Ibañez
 */
public class ModificarFuncion1 extends javax.swing.JFrame {

    /**
     * Creates new form ModificarFuncion2
     */
    public ModificarFuncion1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        opciones = new javax.swing.JComboBox<>();
        btn_atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        triangular = new javax.swing.JRadioButton();
        trapezoidal = new javax.swing.JRadioButton();
        trapezoidalAIzq = new javax.swing.JRadioButton();
        TrapezoidalADer = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        x1 = new javax.swing.JTextField();
        x2 = new javax.swing.JTextField();
        x3 = new javax.swing.JTextField();
        x4 = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALAS", "REGULARES", "BUENAS" }));

        btn_atras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_atras.setText("Atras");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Notas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modificar función");
        jLabel2.setToolTipText("");

        btn_guardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        buttonGroup1.add(triangular);
        triangular.setText("Triangular");
        triangular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangularActionPerformed(evt);
            }
        });

        buttonGroup1.add(trapezoidal);
        trapezoidal.setText("Trapezoidal");
        trapezoidal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trapezoidalActionPerformed(evt);
            }
        });

        buttonGroup1.add(trapezoidalAIzq);
        trapezoidalAIzq.setText("Trapezoidal abierta por la izquierda");
        trapezoidalAIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trapezoidalAIzqActionPerformed(evt);
            }
        });

        buttonGroup1.add(TrapezoidalADer);
        TrapezoidalADer.setText("Trapezoidal abierta por la derecha");
        TrapezoidalADer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrapezoidalADerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tipo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Valores");

        x1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        x2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        x3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        x4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_aceptar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TrapezoidalADer)
                        .addComponent(trapezoidalAIzq)
                        .addComponent(trapezoidal)
                        .addComponent(triangular)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(opciones, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btn_aceptar)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(triangular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trapezoidal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trapezoidalAIzq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TrapezoidalADer)
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_atras))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        // TODO add your handling code here:
        ModificarFuncion mf = new ModificarFuncion();
        mf.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        Archivos a = new Archivos();
        int tipo=0;
        if(triangular.isSelected()){
            tipo = 0;
        } else if(trapezoidal.isSelected()){
            tipo = 1;
        } else if(trapezoidalAIzq.isSelected()){
            tipo = 2;
        } else if(TrapezoidalADer.isSelected()){
            tipo = 3;
        }
        int xx1= Integer.parseInt(x1.getText());
        int xx2= Integer.parseInt(x2.getText());
        int xx3= Integer.parseInt(x3.getText());
        int xx4= Integer.parseInt(x4.getText());
        String opcion = (String)opciones.getSelectedItem();
        try {
            a.modificarDatos("Notas", opcion, tipo, xx1, xx2, xx3, xx4);
            JOptionPane.showMessageDialog(null, "Guardado");
        } catch (IOException ex) {
            Logger.getLogger(ModificarFuncion1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        Archivos a = new Archivos();
        ArrayList <Integer> numeros = new ArrayList();
        try {
            numeros = a.obtenerDatos("Notas",(String)opciones.getSelectedItem());
            if(numeros.get(0)==0){
                triangular.setSelected(true);
                x1.setVisible(false);
                x4.setEditable(true);
                x2.setText(numeros.get(2)+"");
                x3.setText(numeros.get(3)+"");
                x4.setText(numeros.get(4)+"");
            } else if(numeros.get(0)==1){
                trapezoidal.setSelected(true);
                x1.setVisible(true);
                x4.setEditable(true);
                x1.setEditable(true);
                x1.setText(numeros.get(1)+"");
                x2.setText(numeros.get(2)+"");
                x3.setText(numeros.get(3)+"");
                x4.setText(numeros.get(4)+"");
            } else if(numeros.get(0)==2){
                trapezoidalAIzq.setSelected(true);
                x1.setEditable(false);
                x1.setVisible(true);
                x4.setEditable(true);
                x1.setText(numeros.get(1)+"");
                x2.setText(numeros.get(2)+"");
                x3.setText(numeros.get(3)+"");
                x4.setText(numeros.get(4)+"");
            } else if(numeros.get(0)==3){
                TrapezoidalADer.setSelected(true);
                x4.setEditable(false);
                x1.setVisible(true);
                x1.setEditable(true);
                x1.setText(numeros.get(1)+"");
                x2.setText(numeros.get(2)+"");
                x3.setText(numeros.get(3)+"");
                x4.setText(numeros.get(4)+"");
            }
            numeros.clear();
        } catch (IOException ex) {
            Logger.getLogger(ModificarFuncion1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void triangularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangularActionPerformed
        // TODO add your handling code here:
        x1.setVisible(false);
        x4.setEditable(true);
        x1.setText(0+"");
        x2.setText("");
        x3.setText("");
        x4.setText("");
    }//GEN-LAST:event_triangularActionPerformed

    private void trapezoidalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trapezoidalActionPerformed
        // TODO add your handling code here:
        x1.setVisible(true);
        x4.setEditable(true);
        x1.setEditable(true);
        x1.setText("");
        x2.setText("");
        x3.setText("");
        x4.setText("");
    }//GEN-LAST:event_trapezoidalActionPerformed

    private void trapezoidalAIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trapezoidalAIzqActionPerformed
        // TODO add your handling code here:
        x1.setEditable(false);
        x1.setVisible(true);
        x4.setEditable(true);
        x1.setText("-999");
        x2.setText("");
        x3.setText("");
        x4.setText("");
    }//GEN-LAST:event_trapezoidalAIzqActionPerformed

    private void TrapezoidalADerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrapezoidalADerActionPerformed
        // TODO add your handling code here:
        x4.setEditable(false);
        x1.setVisible(true);
        x1.setEditable(true);
        x1.setText("");
        x2.setText("");
        x3.setText("");
        x4.setText("999");
    }//GEN-LAST:event_TrapezoidalADerActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton TrapezoidalADer;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_guardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> opciones;
    private javax.swing.JRadioButton trapezoidal;
    private javax.swing.JRadioButton trapezoidalAIzq;
    private javax.swing.JRadioButton triangular;
    private javax.swing.JTextField x1;
    private javax.swing.JTextField x2;
    private javax.swing.JTextField x3;
    private javax.swing.JTextField x4;
    // End of variables declaration//GEN-END:variables
}
